language: csharp
mono: none
dotnet: 3.1.100
services:
    - docker
before_install: 
    - cd src
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - dotnet restore
script:
    - dotnet build
    - dotnet test
before_deploy: 
    - cd ../
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy-docker.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./deploy-docker.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash ./deploy-docker.sh
    on: 
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./deploy-nuget.sh
    on: 
      tags: true
      branch: master