addons:
  sonarcloud:
    organization: "expenses-api"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
language: csharp
mono: none
dotnet: 3.1.100
install:
- dotnet restore
script:
- dotnet build
- dotnet test
- sonar-scanner
#- dotnet test Expenses.UnitTests/Expenses.UnitTests.csproj
#- dotnet test Expenses.IntegrationTests/Expenses.IntegrationTests.csproj