language: csharp
dist: xenial
mono: none
dotnet: 3.0.*
install:
- dotnet restore
script:
- dotnet build
- dotnet test
#- dotnet test Expenses.UnitTests/Expenses.UnitTests.csproj
#- dotnet test Expenses.IntegrationTests/Expenses.IntegrationTests.csproj