language: csharp
mono: none
dotnet: 2.2.402
install:
- dotnet restore
script:
- dotnet build
- dotnet test
#- dotnet test Expenses.UnitTests/Expenses.UnitTests.csproj
#- dotnet test Expenses.IntegrationTests/Expenses.IntegrationTests.csproj