language: csharp
mono: none
dotnet: 3.1.100
services:
    - docker
before_install: 
    - cd src
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - dotnet restore
script:
    - dotnet build
    - dotnet test
before_deploy: 
    - cd ../
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    tags: true
    branch: master