language: csharp
mono: none
dotnet: 3.1.100
services:
    - docker
before_install: 
    - cd src
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - dotnet restore
script:
    - dotnet build
    - dotnet test
deploy:
  provider: script
  script: bash ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    tag: true