version: "3"
services:
    expenses.api:
        image: expenses-api
        build: 
            context: .
            dockerfile: src/Expenses.API/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"
            ConnectionStrings__ExpensesDatabase: "Server=mssql;Database=expenses;User Id=sa;Password=Network@123;"
            ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672/"
            Telemetry__Jaeger__Enabled: "true"
            Telemetry__Jaeger__AgentHost: "jaeger"
        ports:
            - "8080:80"
        depends_on:
            - mssql
            - rabbitmq
            - jaeger
    expenses.worker.statementcreator:
        image: expenses-worker-statementcreator
        build: 
            context: .
            dockerfile: src/Expenses.Worker.StatementCreator/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"
            ConnectionStrings__ExpensesDatabase: "Server=mssql;Database=expenses;User Id=sa;Password=Network@123;"
            ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672/"
            Telemetry__Jaeger__Enabled: "true"
            Telemetry__Jaeger__AgentHost: "jaeger"
        depends_on:
            - mssql
            - rabbitmq
            - jaeger
            - expenses.api
    mssql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Network@123"
            ACCEPT_EULA: "Y"
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
    jaeger:
        image: jaegertracing/all-in-one
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411